routes/web.php
<?php

Auth::routes();

// Public routes
Route::get('/', 'PublicController@index');

Route::group(['prefix' => 'job'], function () {
    Route::get('/{id}/approve', ['as' => 'approve.job', 'uses' => 'PublicController@approve'])
        ->middleware('auth.token');
    Route::get('/{id}/spam', ['as' => 'spam.job', 'uses' => 'PublicController@spam'])
        ->middleware('auth.token');

    Route::get('/{id}/{slug}', ['as' => 'public.job.details', 'uses' => 'PublicController@show']);

});

// After login routes
Route::get('/home', 'HomeController@index');
Route::resource('/jobs', 'JobsController', ['except' => ['show']]);

Route::group(['prefix' => 'jobs'], function () {
    Route::get('/{id}/{slug}', ['as' => 'jobs.details', 'uses' => 'JobsController@show']);
    Route::post('/{id}/submit', ['as' => 'jobs.submit', 'uses' => 'JobsController@submit']);
    Route::post('/{id}/approve', ['as' => 'jobs.approve', 'uses' => 'JobsController@approve']);
    Route::post('/{id}/spam', ['as' => 'jobs.spam', 'uses' => 'JobsController@spam']);
});

app/Job.php
<?php

namespace App;

use App\Traits\JobPostTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class JobPost
 *
 * @package App
 */
class Job extends Model
{
    use SoftDeletes;
    use JobPostTrait;

    /**
     * @var array
     */
    protected $guarded = ['id'];

    protected $dates = ['approved_date'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/JobsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\JobRequest;
use App\Services\JobsService;
use Illuminate\Http\Request;

class JobsController extends Controller
{
    /**
     * @var \App\Services\JobsService
     */
    private $jobsService;

    /**
     * @param \App\Services\JobsService $jobsService
     */
    public function __construct(JobsService $jobsService)
    {
        $this->middleware('auth');
        $this->jobsService = $jobsService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->get('filter', []);

        $jobs = $this->jobsService->all($filter);

        return view('jobs.index', [
            'jobs' => $jobs,
            'filter' => $filter
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('jobs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\JobRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(JobRequest $request)
    {
        $job = $this->jobsService->store($request->all());

        if (!$job) {
            flash('Failed to create job', 'error');
            return redirect()->back()->withInput();
        }

        flash('Job created successfully. Please submit this if you are done.');

        return redirect()->route('jobs.details', [$job->id, $job->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param         $id
     * @param  string $slug
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id, $slug)
    {
        $job = $this->jobsService->findByIdAndSlug($id, $slug);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        return view('jobs.show')->withJob($job);
    }

    /**
     * Submit job
     *
     * @param $id
     *
     * @return \Illuminate\Http\Response
     */
    public function submit($id)
    {
        $job = $this->jobsService->findUserJobById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $response = $this->jobsService->submitJobForModeration($job);

        flash($response['message'], $response['type']);

        return redirect()->route('jobs.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $job = $this->jobsService->findUserJobById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        if (!$this->jobsService->isEligibleToEdit($job)) {
            flash($job->status . ' job cannot be edit!', 'error');
            return redirect()->route('jobs.index');
        }

        return view('jobs.edit')->withJob($job);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\JobRequest $request
     * @param  int                          $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(JobRequest $request, $id)
    {
        $job = $this->jobsService->findUserJobById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $is_updated = $this->jobsService->update($request->except(['_method', '_token', 'files']), $job);

        if ($is_updated) {
            flash('Job updated successfully!');
        } else {
            flash('Failed to update job!', 'error');
        }

        return redirect()->route('jobs.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $is_deleted = $this->jobsService->deleteJob($id);

        if ($is_deleted) {
            flash('Job deleted successfully!');
        } else {
            flash('Failed to delete job!', 'error');
        }

        return redirect()->route('jobs.index');
    }

    /**
     * Approve job
     *
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function approve($id)
    {
        $job = $this->jobsService->findById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $response = $this->jobsService->approveJob($job);

        flash($response['message'], $response['type']);

        return redirect()->route('jobs.index');
    }

    /**
     * Mark as spam job
     *
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function spam($id)
    {
        $job = $this->jobsService->findById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $response = $this->jobsService->markAsSpamJob($job);

        flash($response['message'], $response['type']);

        return redirect()->route('jobs.index');
    }
}

resources/views/jobs/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h4>New Job</h4></div>
                    <div class="panel-body">
                        <form action="{{route('jobs.store')}}" method="POST" class="form-horizontal">
                            @include('jobs.partials.form')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

    <script>tinymce.init({ selector:'textarea', height: 250 });</script>
@endsection

resources/views/jobs/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h4>Edit Job</h4></div>
                    <div class="panel-body">
                        <form action="{{route('jobs.update', $job->id)}}" method="POST" class="form-horizontal">
                            {{method_field('PUT')}}
                            @include('jobs.partials.form')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

    <script>tinymce.init({ selector:'textarea', height: 250 });</script>
@endsection

resources/views/jobs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="list-group">
                    <form role="search" class="list-group-item">
                        <div class="form-group">
                            <div class="col-md-8">
                                <input type="text" name="filter[q]" value="{{isset($filter['q'])?$filter['q']:null}}" class="form-control" placeholder="Filter title, status">
                            </div>
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-search"></i></button>
                                <a href="{{route('jobs.index')}}" class="btn btn-default"><i class="glyphicon glyphicon-refresh"></i></a>
                            </div>

                            @if (userIsManager())
                            <div class="col-md-2">
                                <a class="btn btn-primary pull-right" title="Create new job" href="{{route('jobs.create')}}">Create New</a>
                            </div>
                            @endif
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="list-group">
                    @forelse($jobs as $job)
                        <a href="{{route('jobs.details', [$job->id, $job->slug])}}" class="list-group-item">
                            {!! $job->statusString() !!}
                            <h4 class="list-group-item-heading"><strong>{{$job->title}}</strong></h4>

                            <p class="list-group-item-text">
                                <i class="glyphicon glyphicon-envelope"></i> {{$job->email}}
                                | <i class="glyphicon glyphicon-calendar"></i> Posted: {{$job->created_at->diffForHumans()}}
                                @if ($job->status === \App\Support\Constants::$job_approved_status)
                                | <i class="glyphicon glyphicon-ok"></i> Approved: {{$job->approved_date->diffForHumans()}}
                                @endif
                            </p>
                        </a>
                    @empty
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading"><strong>No job have found.</strong></h4>
                        </div>
                    @endforelse

                    @if ($jobs->count())
                    <div class="list-group-item">
                        <div class="pull-right">{{$jobs->render()}}</div>
                        <div class="clearfix"></div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jobs/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3> {{$job->title}}
                            <div class="btn-group-sm pull-right">
                                {{--Moderator--}}
                                @include('jobs.partials.actions')
                            </div>
                        </h3>
                    </div>

                    <div class="panel-body">
                        <div class="row">

                            <div class="col-md-3">
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <span class="pull-right">{{$job->created_at->format(config('app.date_format'))}}</span>
                                        Posted At
                                    </li>
                                    <li class="list-group-item">
                                        {!! $job->statusString() !!}
                                        Status
                                    </li>
                                    @if ($job->status === \App\Support\Constants::$job_approved_status)
                                    <li class="list-group-item">
                                        <span class="label label-info pull-right">{{$job->approved_date->format(config('app.date_format'))}}</span>
                                        Approved At
                                    </li>
                                    @endif
                                    <li class="list-group-item">
                                        <span class="pull-right"><i class="glyphicon glyphicon-envelope"></i></span>
                                        {{$job->email}}
                                    </li>
                                </ul>
                            </div>

                            <div class="col-md-9">
                                {!! nl2br($job->description) !!}
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection