routes/web.php
<?php

Auth::routes();

// Public routes
Route::get('/', 'PublicController@index');

Route::group(['prefix' => 'job'], function () {
    Route::get('/{id}/approve', ['as' => 'approve.job', 'uses' => 'PublicController@approve'])
        ->middleware('auth.token');
    Route::get('/{id}/spam', ['as' => 'spam.job', 'uses' => 'PublicController@spam'])
        ->middleware('auth.token');

    Route::get('/{id}/{slug}', ['as' => 'public.job.details', 'uses' => 'PublicController@show']);

});

// After login routes
Route::get('/home', 'HomeController@index');
Route::resource('/jobs', 'JobsController', ['except' => ['show']]);

Route::group(['prefix' => 'jobs'], function () {
    Route::get('/{id}/{slug}', ['as' => 'jobs.details', 'uses' => 'JobsController@show']);
    Route::post('/{id}/submit', ['as' => 'jobs.submit', 'uses' => 'JobsController@submit']);
    Route::post('/{id}/approve', ['as' => 'jobs.approve', 'uses' => 'JobsController@approve']);
    Route::post('/{id}/spam', ['as' => 'jobs.spam', 'uses' => 'JobsController@spam']);
});

app/Job.php
<?php

namespace App;

use App\Traits\JobPostTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class JobPost
 *
 * @package App
 */
class Job extends Model
{
    use SoftDeletes;
    use JobPostTrait;

    /**
     * @var array
     */
    protected $guarded = ['id'];

    protected $dates = ['approved_date'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/JobsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\JobRequest;
use App\Services\JobsService;
use Illuminate\Http\Request;

class JobsController extends Controller
{
    /**
     * @var \App\Services\JobsService
     */
    private $jobsService;

    /**
     * @param \App\Services\JobsService $jobsService
     */
    public function __construct(JobsService $jobsService)
    {
        $this->middleware('auth');
        $this->jobsService = $jobsService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->get('filter', []);

        $jobs = $this->jobsService->all($filter);

        return view('jobs.index', [
            'jobs' => $jobs,
            'filter' => $filter
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('jobs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\JobRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(JobRequest $request)
    {
        $job = $this->jobsService->store($request->all());

        if (!$job) {
            flash('Failed to create job', 'error');
            return redirect()->back()->withInput();
        }

        flash('Job created successfully. Please submit this if you are done.');

        return redirect()->route('jobs.details', [$job->id, $job->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param         $id
     * @param  string $slug
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id, $slug)
    {
        $job = $this->jobsService->findByIdAndSlug($id, $slug);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        return view('jobs.show')->withJob($job);
    }

    /**
     * Submit job
     *
     * @param $id
     *
     * @return \Illuminate\Http\Response
     */
    public function submit($id)
    {
        $job = $this->jobsService->findUserJobById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $response = $this->jobsService->submitJobForModeration($job);

        flash($response['message'], $response['type']);

        return redirect()->route('jobs.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $job = $this->jobsService->findUserJobById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        if (!$this->jobsService->isEligibleToEdit($job)) {
            flash($job->status . ' job cannot be edit!', 'error');
            return redirect()->route('jobs.index');
        }

        return view('jobs.edit')->withJob($job);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\JobRequest $request
     * @param  int                          $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(JobRequest $request, $id)
    {
        $job = $this->jobsService->findUserJobById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $is_updated = $this->jobsService->update($request->except(['_method', '_token', 'files']), $job);

        if ($is_updated) {
            flash('Job updated successfully!');
        } else {
            flash('Failed to update job!', 'error');
        }

        return redirect()->route('jobs.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $is_deleted = $this->jobsService->deleteJob($id);

        if ($is_deleted) {
            flash('Job deleted successfully!');
        } else {
            flash('Failed to delete job!', 'error');
        }

        return redirect()->route('jobs.index');
    }

    /**
     * Approve job
     *
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function approve($id)
    {
        $job = $this->jobsService->findById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $response = $this->jobsService->approveJob($job);

        flash($response['message'], $response['type']);

        return redirect()->route('jobs.index');
    }

    /**
     * Mark as spam job
     *
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function spam($id)
    {
        $job = $this->jobsService->findById($id);

        if (!$job) {
            flash('Item not found!', 'error');
            return redirect()->route('jobs.index');
        }

        $response = $this->jobsService->markAsSpamJob($job);

        flash($response['message'], $response['type']);

        return redirect()->route('jobs.index');
    }
}

resources/views/jobs/partials/actions.blade.php
@if (userIsModerator() && ($job->status === \App\Support\Constants::$job_submitted_status))
    <form action="{{route('jobs.approve', $job->id)}}" method="POST" style="display: inline" onsubmit="return confirm('Are you sure?')">
        {{csrf_field()}}
        <button type="submit" class="btn btn-success btn-sm">Approve</button>
    </form>

    <form action="{{route('jobs.spam', $job->id)}}" method="POST" style="display: inline" onsubmit="return confirm('Are you sure?')">
        {{csrf_field()}}
        <button type="submit" class="btn btn-danger btn-sm">Mark as Spam</button>
    </form>
@endif

@if(userIsManager() && in_array($job->status, \App\Support\Constants::$can_delete_status_list))
    <form action="{{route('jobs.destroy', $job->id)}}" method="POST" style="display: inline" onsubmit="return confirm('Are you sure?')">
        {{csrf_field()}}
        {{method_field('DELETE')}}
        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
    </form>
@endif


@if($job->status == \App\Support\Constants::$job_draft_status)
    <a class="btn btn-primary" href="{{route('jobs.edit', $job->id)}}">Edit</a>
    <form action="{{route('jobs.submit', $job->id)}}" method="POST" style="display: inline" onsubmit="return confirm('Are you sure?')">
        {{csrf_field()}}
        <button type="submit" class="btn btn-success btn-sm">Submit</button>
    </form>
@endif

<a class="btn btn-default" href="{{route('jobs.index')}}">Back</a>

resources/views/jobs/partials/form.blade.php
<div class="form-body">
    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
        <label class="col-md-3 control-label">Title</label>
        <div class="col-md-6">
            <input type="text" name="title" value="{{old('title', isset($job) ? $job->title:null)}}" class="form-control" placeholder="Enter text">
            @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-3 control-label">Email Address</label>
        <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-envelope"></i>
                </span>
                <input type="text" class="form-control" name="email" value="{{old('email', isset($job) ? $job->email:null)}}" placeholder="Email Address">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-3 control-label">Description</label>
        <div class="col-md-9">
            <textarea class="summernote" name="description">{!! old('description', isset($job) ? $job->description : null) !!}</textarea>
        </div>
    </div>

    <div class="form-actions fluid">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{route('jobs.index')}}" class="btn btn-default">Cancel</a>
                <span class="pull-right"> <label class="label label-info">Info!!</label> All fields are required.</span>
            </div>
        </div>
    </div>
</div>
{{csrf_field()}}